import { APP_NAME } from "@/lib/brand";
import type { Role } from "@/lib/constants";

export type HelpArticle = {
  id: string;
  title: string;
  hrefs: string[];
  roles?: Role[];
  keywords: string[];
  body: string;
};

export function helpArticles(): HelpArticle[] {
  return [
    {
      id: "overview",
      title: `What ${APP_NAME} is for`,
      hrefs: ["/guide", "/privacy"],
      keywords: ["overview", "purpose", "use", "site", "app", "how", "start", "begin"],
      body: `${APP_NAME} helps special education teams record IEP goals as they are written, log session progress, and share parent-friendly reports. It does not generate IEP goals, recommend services, or make educational, legal, or clinical decisions. Demonstration data is fictional. Do not enter real student records in demo mode. Start with the setup guide, then work from the dashboard (staff) or family home (parents).`,
    },
    {
      id: "roles",
      title: "Roles and who can see what",
      hrefs: ["/team", "/privacy"],
      keywords: ["role", "roles", "access", "permission", "admin", "educator", "provider", "parent", "guardian", "who", "see"],
      body: "Administrators see every student in the organization and manage team accounts. Educators see students they case-manage and can add goals and session notes. Related-service providers see only assigned students and can log sessions, not create goals. Parents and guardians see only linked students, and only goals the school has shared. Open Team to invite people with the least access they need.",
    },
    {
      id: "students",
      title: "Student profiles",
      hrefs: ["/students", "/students/new"],
      roles: ["ADMINISTRATOR", "EDUCATOR", "PROVIDER"],
      keywords: ["student", "students", "profile", "caseload", "add", "preferred", "name", "grade", "school"],
      body: "Open Students to see your caseload. Add a profile with preferred name, grade, school, case manager, providers, and guardian contacts only. Extra identifiers do not belong here. Filter by name, school, or grade. Open a profile to view goals, IEP review dates, and present levels the team already entered.",
    },
    {
      id: "goals",
      title: "Recording IEP goals",
      hrefs: ["/students", "/guide"],
      roles: ["ADMINISTRATOR", "EDUCATOR"],
      keywords: ["goal", "goals", "iep", "wording", "baseline", "target", "mastery", "objective"],
      body: "Copy official IEP wording into the goal. Add a plain-language summary families can read. Set baseline, measurable target, measurement method, service area, reporting dates, and the mastery rule (consecutive sessions and allowed prompts). You may add short-term objectives. Do not invent goals in this app—transcribe what the IEP already says. Providers can view goals; they do not create them.",
    },
    {
      id: "sessions",
      title: "Logging a session",
      hrefs: ["/dashboard"],
      roles: ["ADMINISTRATOR", "EDUCATOR", "PROVIDER"],
      keywords: ["session", "log", "progress", "trial", "independent", "prompted", "incorrect", "absent", "minutes"],
      body: "From the dashboard or a goal page, open Log progress. For a present session, tap independent, prompted, or incorrect for each trial, add service minutes, setting, and optional notes. Mark absent, declined, or makeup when the service was not delivered. Charts and on-track indicators follow the written mastery rule and describe data only—they are not IEP decisions.",
    },
    {
      id: "reports",
      title: "Progress reports and meeting packets",
      hrefs: ["/reports"],
      keywords: ["report", "reports", "period", "progress", "code", "print", "meeting", "packet", "narrative"],
      body: "Open Reports, choose a student and reporting period, then pick an IEP progress code (sufficient, insufficient, goal met, or not introduced) and write a short narrative. Print a parent-friendly report or an annual meeting packet. Codes and narratives are the team's professional judgment recorded in the app, not advice generated by a chatbot.",
    },
    {
      id: "search",
      title: "Search",
      hrefs: ["/search", "/students"],
      roles: ["ADMINISTRATOR", "EDUCATOR", "PROVIDER"],
      keywords: ["search", "find", "lookup", "wcpm", "reading", "header"],
      body: "Staff can search from the header. Matching is case-insensitive. Students match on preferred name, school, or grade. Goals match official wording, plain-language summary, measurable target, service area, or student name across your permitted caseload. Results never include records you are not allowed to see.",
    },
    {
      id: "messages",
      title: "Messages",
      hrefs: ["/messages"],
      keywords: ["message", "messages", "thread", "family", "staff", "note", "contact"],
      body: "Use Messages for school-to-family threads (FAMILY) versus staff-only notes (STAFF). Parents only see family-visible messages for their linked students. Do not put extra identifiers or other families' information in a thread.",
    },
    {
      id: "family",
      title: "Family portal",
      hrefs: ["/parent"],
      roles: ["PARENT"],
      keywords: ["family", "parent", "guardian", "portal", "home", "child", "children", "switch"],
      body: "Family home shows shared goals, everyday-language progress, reports, and messages for linked students only. If more than one child is linked, use the tabs at the top to switch. You cannot see other families. Ask the school to link this account if no student appears.",
    },
    {
      id: "dashboard",
      title: "Educator dashboard",
      hrefs: ["/dashboard"],
      roles: ["ADMINISTRATOR", "EDUCATOR", "PROVIDER"],
      keywords: ["dashboard", "deadline", "reporting", "review", "minutes", "gap", "stale"],
      body: "The dashboard lists reporting dates in the next 14 days, goals waiting for a present-session note, annual IEP reviews in the next 30 days, and services below this week's prescribed minutes. Use it as a work list. It does not decide whether a goal is met for the IEP.",
    },
    {
      id: "privacy",
      title: "Privacy, consent, and retention",
      hrefs: ["/privacy", "/privacy-notice"],
      keywords: ["privacy", "ferpa", "consent", "retention", "delete", "audit", "export"],
      body: "Read the privacy notice and record consent on Privacy. Administrators set retention and can delete records with confirmation. Authorized staff can export a CSV of their caseload and review audit history. This product follows FERPA-oriented practices; it is not a legal certification.",
    },
    {
      id: "demo",
      title: "Demonstration accounts",
      hrefs: ["/sign-in", "/guide"],
      keywords: ["demo", "sign", "login", "password", "account", "fictional"],
      body: "This site ships fictional demonstration people so you can click every role. Sign in from the sign-in page with a listed demo email. Do not treat demo students as real. Do not type real student records while demonstration mode is on.",
    },
  ];
}
