name: Bug

description: Broken behavior in the app or in Docker / Kubernetes.
title: ""
labels: ["bug"]
body:
  - type: textarea
    id: steps
    attributes:
      label: Steps
      description: How to reproduce.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual
    validations:
      required: true
